In [1]:
from helper_functions import import_flight_data, extract_wind_data
import sys
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [2]:
data_dir = '/Users/rasmus/Desktop/Fysik/AppliedML2026/Final_project_data/data/ML_data/NBI/FDM data'
wind_dir = '/Users/rasmus/Desktop/Fysik/AppliedML2026/Final_project_data/data/ML_data/TWI data'

df = import_flight_data(data_dir=data_dir,limit=1, recursive=True)

In [3]:
COLUMN_MAP = {
    # time
    "Year": "year",
    "QAR YEAR": "year",
    "Date: Year (Derived)": "year",

    "MONTH": "month",
    "QAR MONTH": "month",
    "Date (month)": "month",

    "DAY": "day",
    "QAR DAY": "day",
    "Date (day)": "day",

    "GMT - Hours (BCD)": "hour",
    "QAR HOUR": "hour",
    "UTC Hours": "hour",

    "GMT - Minutes (BCD)": "minute",
    "QAR MINUTE": "minute",
    "UTC Minutes": "minute",

    "GMT Seconds": "second",
    "QAR SECOND": "second",
    "UTC Seconds": "second",

    # altitude
    "Radio Altitude": "radio_altitude",
    "Radio Height 1": "radio_altitude",

    # vertical acceleration
    "Vertical Acceleration": "vert_acc",
    "Normal acceleration": "vert_acc",
}

In [4]:
N_arrivals = 1

arrival_data = import_flight_data(data_dir=data_dir, 
    limit=N_arrivals, add_source_file=True)#, usecols=['Time (secs)','MONTH', 'DAY', 'Year', 'GMT - Hours (BCD)', 'GMT - Minutes (BCD)', 'GMT Seconds', 'Vertical Acceleration', 'Radio Altitude'])

#arrival_data.columns.tolist()

In [5]:
N_arrivals_tot = 3140
N_arrivals = N_arrivals_tot

arrival_data = import_flight_data(data_dir=data_dir,
    limit=N_arrivals, add_source_file=True, usecols=['month', 'day', 'year', 'hour', 'minute', 'second', 'vert_acc', 'radio_altitude'])

In [7]:
from pathlib import Path
from typing import Optional, Union
import numpy as np

import pandas as pd

COLUMN_MAP = {
    # time
    "Year": "year",
    "QAR YEAR": "year",
    "Date: Year (Derived)": "year",

    "MONTH": "month",
    "QAR MONTH": "month",
    "Date (month)": "month",

    "DAY": "day",
    "QAR DAY": "day",
    "Date (day)": "day",

    "GMT - Hours (BCD)": "hour",
    "QAR HOUR": "hour",
    "UTC Hours": "hour",

    "GMT - Minutes (BCD)": "minute",
    "QAR MINUTE": "minute",
    "UTC Minutes": "minute",

    "GMT Seconds": "second",
    "QAR SECOND": "second",
    "UTC Seconds": "second",

    # altitude
    "Radio Altitude": "radio_altitude",
    "Radio Height 1": "radio_altitude",

    # vertical acceleration
    "Vertical Acceleration": "vert_acc",
    "Normal acceleration": "vert_acc",
}

def import_flight_data(
    data_dir: Optional[Union[str, Path]] = None,
    pattern: str = "*.csv",
    recursive: bool = True,
    start: Optional[int] = 0,
    limit: Optional[int] = None,
    add_source_file: bool = True,
    **read_csv_kwargs,
) -> pd.DataFrame:
    """
    Import CSV flight data from the turbulens data folder.

    Args:
        data_dir: Directory to search. Defaults to `<project_root>/data`.
        pattern: File match pattern, default is '*.csv'.
        recursive: If True, search subfolders recursively.
        start: Optional index to start loading files from.
        limit: Optional max number of files to load.
        add_source_file: If True, add a `source_file` column.
        **read_csv_kwargs: Extra keyword arguments passed to `pd.read_csv`.

    Returns:
        A concatenated pandas DataFrame containing all loaded CSV files.
    """
    root_data_dir = Path(__file__).resolve().parents[1] / "data"
    target_dir = Path(data_dir) if data_dir else root_data_dir

    finder = "rglob" if recursive else "glob"

    arrivals_dir = target_dir / "Arrivals"
    departures_dir = target_dir / "Departures"

    arrivals = sorted(getattr(arrivals_dir, finder)(pattern))
    departures = sorted(getattr(departures_dir, finder)(pattern))
    csv_files = arrivals + departures


    if limit is not None:
        csv_files = csv_files[start:start + limit]
    else:
        csv_files = csv_files[start:]

    if not csv_files:
        raise FileNotFoundError(
            f"No files found in '{target_dir}' using pattern '{pattern}'."
        )

    frames = []
    for csv_path in csv_files:
        if 'GKN' in csv_path.name: #Skip files with OY-GKN, as their format sucks
            continue
        frame = pd.read_csv(csv_path, low_memory=False)

        frame.columns = [COLUMN_MAP.get(c, c) for c in frame.columns]       
        needed = [
            'year','month','day',
            'hour','minute','second',
            'vert_acc','radio_altitude']      
          
        frame = frame[[c for c in needed if c in frame.columns]]        
        mask_time = np.isclose(frame['second'] % 1, 0) #!!!
        mask_alt = frame['radio_altitude'] <= 1500 #!!!
        frame = frame.loc[mask_time & mask_alt].reset_index(drop=True) #!!!

        if add_source_file:
            frame["source_file"] = str(csv_path)
        frames.append(frame)

    return pd.concat(frames, ignore_index=True)

def extract_wind_data(flight_df, data_dir, offset=10): 
    """
    Extracts wind data from the TWI dataset for a given flight, based on the landing time and an offset for the recording start time.
    Args:
        flight_df (pd.DataFrame): A DataFrame containing data for one flight, including landing time information.
        data_dir (str): The directory containing the wind data files.
        offset (int): The number of minutes before the landing time to start recording wind data. Default is 10 minutes.
    Returns:
        pd.DataFrame: A DataFrame containing the wind data for the specified time range.
    """

    first = flight_df.iloc[0]

    month = first['month'].astype(int)
    day = first['day'].astype(int)
    if day < 10:
        day_string = '0'+str(day)
    else:
        day_string = str(day)

    if month < 10:
        month_string = '0'+str(month)
    else:        
        month_string = str(month)

    year = first['year'].astype(int)
    start_h = first['hour'].astype(int)
    start_m = first['minute'].astype(int)
    start_s = first['second'].astype(int)
    
    start_of_landing_time = pd.Timestamp(year=year,month=month,day=day,hour=start_h,minute=start_m,second=start_s)

    start_of_recording_time = start_of_landing_time - pd.Timedelta(minutes=offset)
    
    if start_of_recording_time.day != start_of_landing_time.day:
        raise ValueError("Start of recording time is on a different day than the landing time. Please adjust the offset or check the flight data.")
    
    date_string = str(year)+'-'+month_string+'-'+day_string
    file_string = 'TWI-'+date_string+'_UTC_log.csv'

    wind_df = pd.read_csv(data_dir + '/' + file_string, sep=';')

    wind_df['DateTime'] = pd.to_datetime(wind_df['DateTime'], format='%Y-%m-%d %H:%M:%S')

    mask_time = (wind_df['DateTime'] >= start_of_recording_time) & (wind_df['DateTime'] <= start_of_landing_time)

    wind_df = wind_df.loc[mask_time].reset_index(drop=True)
    wind_df['source_file'] = first['source_file']
    return wind_df

In [8]:
full_wind_data = []
idx = 0

for flight_id, flight_df in arrival_data.groupby('source_file'):
    idx +=1
    print(f"Processing flight: {idx}/{len(arrival_data.groupby('source_file'))}")
    try:
        wind_df = extract_wind_data(flight_df, data_dir=wind_dir)
        wind_df['source_file'] = flight_id
        full_wind_data.append(wind_df)

    except ValueError as e:
        print(f"Error processing flight {flight_id}: {e}")
full_wind_data = pd.concat(full_wind_data, ignore_index=True)
full_wind_data.to_csv('/Users/rasmus/Desktop/Fysik/AppliedML2026/AppMLFinalProject.csv', index=False)

Processing flight: 1/2890
Processing flight: 2/2890
Processing flight: 3/2890
Processing flight: 4/2890
Processing flight: 5/2890
Processing flight: 6/2890
Processing flight: 7/2890
Processing flight: 8/2890
Processing flight: 9/2890
Processing flight: 10/2890
Processing flight: 11/2890
Processing flight: 12/2890
Processing flight: 13/2890
Processing flight: 14/2890
Processing flight: 15/2890
Processing flight: 16/2890
Processing flight: 17/2890
Processing flight: 18/2890
Processing flight: 19/2890
Processing flight: 20/2890
Processing flight: 21/2890
Processing flight: 22/2890
Processing flight: 23/2890
Processing flight: 24/2890
Processing flight: 25/2890
Processing flight: 26/2890
Processing flight: 27/2890
Processing flight: 28/2890
Processing flight: 29/2890
Processing flight: 30/2890
Processing flight: 31/2890
Processing flight: 32/2890
Processing flight: 33/2890
Processing flight: 34/2890
Processing flight: 35/2890
Processing flight: 36/2890
Processing flight: 37/2890
Processing flight: 38/2890
Processing flight: 39/2890
Processing flight: 40/2890
Processing flight: 41/2890
Processing flight: 42/2890
Processing flight: 43/2890
Processing flight: 44/2890
Processing flight: 45/2890
Processing flight: 46/2890
Processing flight: 47/2890
Processing flight: 48/2890
Processing flight: 49/2890
Processing flight: 50/2890
Processing flight: 51/2890
Processing flight: 52/2890
Processing flight: 53/2890
Processing flight: 54/2890
Processing flight: 55/2890
Processing flight: 56/2890
Processing flight: 57/2890
Processing flight: 58/2890
Processing flight: 59/2890
Processing flight: 60/2890
Processing flight: 61/2890
Processing flight: 62/2890
Processing flight: 63/2890
Processing flight: 64/2890
Processing flight: 65/2890
Processing flight: 66/2890
Processing flight: 67/2890
Processing flight: 68/2890
Processing flight: 69/2890
Processing flight: 70/2890
Processing flight: 71/2890
Processing flight: 72/2890
Processing flight: 73/2890
Processing flight: 74/2890
Processing flight: 75/2890
Processing flight: 76/2890
Processing flight: 77/2890
Processing flight: 78/2890
Processing flight: 79/2890
Processing flight: 80/2890
Processing flight: 81/2890
Processing flight: 82/2890
Processing flight: 83/2890
Processing flight: 84/2890
Processing flight: 85/2890
Processing flight: 86/2890
Processing flight: 87/2890
Processing flight: 88/2890
Processing flight: 89/2890
Processing flight: 90/2890
Processing flight: 91/2890
Processing flight: 92/2890
Processing flight: 93/2890
Processing flight: 94/2890
Processing flight: 95/2890
Processing flight: 96/2890
Processing flight: 97/2890
Processing flight: 98/2890
Processing flight: 99/2890
Processing flight: 100/2890
Processing flight: 101/2890
Processing flight: 102/2890
Processing flight: 103/2890
Processing flight: 104/2890
Processing flight: 105/2890
Processing flight: 106/2890
Processing flight: 107/2890
Processing flight: 108/2890
Processing flight: 109/2890
Processing flight: 110/2890
Processing flight: 111/2890
Processing flight: 112/2890
Processing flight: 113/2890
Processing flight: 114/2890
Processing flight: 115/2890
Processing flight: 116/2890
Processing flight: 117/2890
Processing flight: 118/2890
Processing flight: 119/2890
Processing flight: 120/2890
Processing flight: 121/2890
Processing flight: 122/2890
Processing flight: 123/2890
Processing flight: 124/2890
Processing flight: 125/2890
Processing flight: 126/2890
Processing flight: 127/2890
Processing flight: 128/2890
Processing flight: 129/2890
Processing flight: 130/2890
Processing flight: 131/2890
Processing flight: 132/2890
Processing flight: 133/2890
Processing flight: 134/2890
Processing flight: 135/2890
Processing flight: 136/2890
Processing flight: 137/2890
Processing flight: 138/2890
Processing flight: 139/2890
Processing flight: 140/2890
Processing flight: 141/2890
Processing flight: 142/2890
Processing flight: 143/2890
Processing flight: 144/2890
Processing flight: 145/2890
Processing flight: 146/2890
Processing flight: 147/2890
Processing flight: 148/2890
Processing flight: 149/2890
Processing flight: 150/2890
Processing flight: 151/2890
Processing flight: 152/2890
Processing flight: 153/2890
Processing flight: 154/2890
Processing flight: 155/2890
Processing flight: 156/2890
Processing flight: 157/2890
Processing flight: 158/2890
Processing flight: 159/2890
Processing flight: 160/2890
Processing flight: 161/2890
Processing flight: 162/2890
Processing flight: 163/2890
Processing flight: 164/2890
Processing flight: 165/2890
Processing flight: 166/2890
Processing flight: 167/2890
Processing flight: 168/2890
Processing flight: 169/2890
Processing flight: 170/2890
Processing flight: 171/2890
Processing flight: 172/2890
Processing flight: 173/2890
Processing flight: 174/2890
Processing flight: 175/2890
Processing flight: 176/2890
Processing flight: 177/2890
Processing flight: 178/2890
Processing flight: 179/2890
Processing flight: 180/2890
Processing flight: 181/2890
Processing flight: 182/2890
Processing flight: 183/2890
Processing flight: 184/2890
Processing flight: 185/2890
Processing flight: 186/2890
Processing flight: 187/2890
Processing flight: 188/2890
Processing flight: 189/2890
Processing flight: 190/2890
Processing flight: 191/2890
Processing flight: 192/2890
Processing flight: 193/2890
Processing flight: 194/2890
Processing flight: 195/2890
Processing flight: 196/2890
Processing flight: 197/2890
Processing flight: 198/2890
Processing flight: 199/2890
Processing flight: 200/2890
Processing flight: 201/2890
Processing flight: 202/2890
Processing flight: 203/2890
Processing flight: 204/2890
Processing flight: 205/2890
Processing flight: 206/2890
Processing flight: 207/2890
Processing flight: 208/2890
Processing flight: 209/2890
Processing flight: 210/2890
Processing flight: 211/2890
Processing flight: 212/2890
Processing flight: 213/2890
Processing flight: 214/2890
Processing flight: 215/2890
Processing flight: 216/2890
Processing flight: 217/2890
Processing flight: 218/2890
Processing flight: 219/2890
Processing flight: 220/2890
Processing flight: 221/2890
Processing flight: 222/2890
Processing flight: 223/2890
Processing flight: 224/2890
Processing flight: 225/2890
Processing flight: 226/2890
Processing flight: 227/2890
Processing flight: 228/2890
Processing flight: 229/2890
Processing flight: 230/2890
Processing flight: 231/2890
Processing flight: 232/2890
Processing flight: 233/2890
Processing flight: 234/2890
Processing flight: 235/2890
Processing flight: 236/2890
Processing flight: 237/2890
Processing flight: 238/2890
Processing flight: 239/2890
Processing flight: 240/2890
Processing flight: 241/2890
Processing flight: 242/2890
Processing flight: 243/2890
Processing flight: 244/2890
Processing flight: 245/2890
Processing flight: 246/2890
Processing flight: 247/2890
Processing flight: 248/2890
Processing flight: 249/2890
Processing flight: 250/2890
Processing flight: 251/2890
Processing flight: 252/2890
Processing flight: 253/2890
Processing flight: 254/2890
Processing flight: 255/2890
Processing flight: 256/2890
Processing flight: 257/2890
Processing flight: 258/2890
Processing flight: 259/2890
Processing flight: 260/2890
Processing flight: 261/2890
Processing flight: 262/2890
Processing flight: 263/2890
Processing flight: 264/2890
Processing flight: 265/2890
Processing flight: 266/2890
Processing flight: 267/2890
Processing flight: 268/2890
Processing flight: 269/2890
Processing flight: 270/2890
Processing flight: 271/2890
Processing flight: 272/2890
Processing flight: 273/2890
Processing flight: 274/2890
Processing flight: 275/2890
Processing flight: 276/2890
Processing flight: 277/2890
Processing flight: 278/2890
Processing flight: 279/2890
Processing flight: 280/2890
Processing flight: 281/2890
Processing flight: 282/2890
Processing flight: 283/2890
Processing flight: 284/2890
Processing flight: 285/2890
Processing flight: 286/2890
Processing flight: 287/2890
Processing flight: 288/2890
Processing flight: 289/2890
Processing flight: 290/2890
Processing flight: 291/2890
Processing flight: 292/2890
Processing flight: 293/2890
Processing flight: 294/2890
Processing flight: 295/2890
Processing flight: 296/2890
Processing flight: 297/2890
Processing flight: 298/2890
Processing flight: 299/2890
Processing flight: 300/2890
Processing flight: 301/2890
Processing flight: 302/2890
Processing flight: 303/2890
Processing flight: 304/2890
Processing flight: 305/2890
Processing flight: 306/2890
Processing flight: 307/2890
Processing flight: 308/2890
Processing flight: 309/2890
Processing flight: 310/2890
Processing flight: 311/2890
Processing flight: 312/2890
Processing flight: 313/2890
Processing flight: 314/2890
Processing flight: 315/2890
Processing flight: 316/2890
Processing flight: 317/2890
Processing flight: 318/2890
Processing flight: 319/2890
Processing flight: 320/2890
Processing flight: 321/2890
Processing flight: 322/2890
Processing flight: 323/2890
Processing flight: 324/2890
Processing flight: 325/2890
Processing flight: 326/2890
Processing flight: 327/2890
Processing flight: 328/2890
Processing flight: 329/2890
Processing flight: 330/2890
Processing flight: 331/2890
Processing flight: 332/2890
Processing flight: 333/2890
Processing flight: 334/2890
Processing flight: 335/2890
Processing flight: 336/2890
Processing flight: 337/2890
Processing flight: 338/2890
Processing flight: 339/2890
Processing flight: 340/2890
Processing flight: 341/2890
Processing flight: 342/2890
Processing flight: 343/2890
Processing flight: 344/2890
Error processing flight /Users/rasmus/Desktop/Fysik/AppliedML2026/Final_project_data/data/ML_data/NBI/FDM data/Arrivals/Nuuk Arrival_ 209598_OY-GRH_14_01_25_01_19.csv: minute must be in 0..59
Processing flight: 345/2890
Processing flight: 346/2890
Processing flight: 347/2890
Processing flight: 348/2890
Processing flight: 349/2890
Processing flight: 350/2890
Processing flight: 351/2890
Processing flight: 352/2890
Processing flight: 353/2890
Processing flight: 354/2890
Processing flight: 355/2890
Processing flight: 356/2890
Processing flight: 357/2890
Processing flight: 358/2890
Processing flight: 359/2890
Processing flight: 360/2890
Processing flight: 361/2890
Processing flight: 362/2890
Processing flight: 363/2890
Processing flight: 364/2890
Processing flight: 365/2890
Processing flight: 366/2890
Processing flight: 367/2890
Processing flight: 368/2890
Processing flight: 369/2890
Processing flight: 370/2890
Processing flight: 371/2890
Processing flight: 372/2890
Processing flight: 373/2890
Processing flight: 374/2890
Processing flight: 375/2890
Processing flight: 376/2890
Processing flight: 377/2890
Processing flight: 378/2890
Processing flight: 379/2890
Processing flight: 380/2890
Processing flight: 381/2890
Processing flight: 382/2890
Processing flight: 383/2890
Processing flight: 384/2890
Processing flight: 385/2890
Processing flight: 386/2890
Processing flight: 387/2890
Processing flight: 388/2890
Processing flight: 389/2890
Processing flight: 390/2890
Processing flight: 391/2890
Processing flight: 392/2890
Processing flight: 393/2890
Processing flight: 394/2890
Processing flight: 395/2890
Processing flight: 396/2890
Processing flight: 397/2890
Processing flight: 398/2890
Processing flight: 399/2890
Processing flight: 400/2890
Processing flight: 401/2890
Processing flight: 402/2890
Processing flight: 403/2890
Processing flight: 404/2890
Processing flight: 405/2890
Processing flight: 406/2890
Processing flight: 407/2890
Processing flight: 408/2890
Processing flight: 409/2890
Processing flight: 410/2890
Processing flight: 411/2890
Processing flight: 412/2890
Processing flight: 413/2890
Processing flight: 414/2890
Processing flight: 415/2890
Processing flight: 416/2890
Processing flight: 417/2890
Processing flight: 418/2890
Processing flight: 419/2890
Processing flight: 420/2890
Processing flight: 421/2890
Processing flight: 422/2890
Processing flight: 423/2890
Processing flight: 424/2890
Processing flight: 425/2890
Processing flight: 426/2890
Processing flight: 427/2890
Processing flight: 428/2890
Processing flight: 429/2890
Processing flight: 430/2890
Processing flight: 431/2890
Processing flight: 432/2890
Processing flight: 433/2890
Processing flight: 434/2890
Processing flight: 435/2890
Processing flight: 436/2890
Processing flight: 437/2890
Processing flight: 438/2890
Processing flight: 439/2890
Processing flight: 440/2890
Processing flight: 441/2890
Processing flight: 442/2890
Processing flight: 443/2890
Processing flight: 444/2890
Processing flight: 445/2890
Processing flight: 446/2890
Processing flight: 447/2890
Processing flight: 448/2890
Processing flight: 449/2890
Processing flight: 450/2890
Processing flight: 451/2890
Processing flight: 452/2890
Processing flight: 453/2890
Processing flight: 454/2890
Processing flight: 455/2890
Processing flight: 456/2890
Processing flight: 457/2890
Error processing flight /Users/rasmus/Desktop/Fysik/AppliedML2026/Final_project_data/data/ML_data/NBI/FDM data/Arrivals/Nuuk Arrival_ 210293_OY-GRP_01_02_25_01_15.csv: minute must be in 0..59
Processing flight: 458/2890
Processing flight: 459/2890
Processing flight: 460/2890
Processing flight: 461/2890
Processing flight: 462/2890
Processing flight: 463/2890
Processing flight: 464/2890
Processing flight: 465/2890
Processing flight: 466/2890
Processing flight: 467/2890
Processing flight: 468/2890
Processing flight: 469/2890
Processing flight: 470/2890
Processing flight: 471/2890
Processing flight: 472/2890
Processing flight: 473/2890
Processing flight: 474/2890
Processing flight: 475/2890
Processing flight: 476/2890
Processing flight: 477/2890
Processing flight: 478/2890
Processing flight: 479/2890
Processing flight: 480/2890
Processing flight: 481/2890
Processing flight: 482/2890
Processing flight: 483/2890
Processing flight: 484/2890
Processing flight: 485/2890
Processing flight: 486/2890
Processing flight: 487/2890
Processing flight: 488/2890
Processing flight: 489/2890
Processing flight: 490/2890
Processing flight: 491/2890
Processing flight: 492/2890
Processing flight: 493/2890
Processing flight: 494/2890
Processing flight: 495/2890
Processing flight: 496/2890
Processing flight: 497/2890
Processing flight: 498/2890
Processing flight: 499/2890
Processing flight: 500/2890
Processing flight: 501/2890
Processing flight: 502/2890
Processing flight: 503/2890
Processing flight: 504/2890
Processing flight: 505/2890
Processing flight: 506/2890
Processing flight: 507/2890
Processing flight: 508/2890
Processing flight: 509/2890
Processing flight: 510/2890
Processing flight: 511/2890
Processing flight: 512/2890
Processing flight: 513/2890
Processing flight: 514/2890
Processing flight: 515/2890
Processing flight: 516/2890
Processing flight: 517/2890
Processing flight: 518/2890
Processing flight: 519/2890
Processing flight: 520/2890
Processing flight: 521/2890
Processing flight: 522/2890
Processing flight: 523/2890
Processing flight: 524/2890
Processing flight: 525/2890
Processing flight: 526/2890
Processing flight: 527/2890
Processing flight: 528/2890
Processing flight: 529/2890
Processing flight: 530/2890
Processing flight: 531/2890
Processing flight: 532/2890
Processing flight: 533/2890
Processing flight: 534/2890
Processing flight: 535/2890
Processing flight: 536/2890
Processing flight: 537/2890
Processing flight: 538/2890
Processing flight: 539/2890
Processing flight: 540/2890
Processing flight: 541/2890
Processing flight: 542/2890
Processing flight: 543/2890
Processing flight: 544/2890
Processing flight: 545/2890
Processing flight: 546/2890
Processing flight: 547/2890
Processing flight: 548/2890
Processing flight: 549/2890
Processing flight: 550/2890
Processing flight: 551/2890
Processing flight: 552/2890
Processing flight: 553/2890
Processing flight: 554/2890
Processing flight: 555/2890
Processing flight: 556/2890
Processing flight: 557/2890
Processing flight: 558/2890
Processing flight: 559/2890
Processing flight: 560/2890
Processing flight: 561/2890
Processing flight: 562/2890
Processing flight: 563/2890
Processing flight: 564/2890
Processing flight: 565/2890
Processing flight: 566/2890
Processing flight: 567/2890
Processing flight: 568/2890
Processing flight: 569/2890
Processing flight: 570/2890
Processing flight: 571/2890
Processing flight: 572/2890
Processing flight: 573/2890
Processing flight: 574/2890
Processing flight: 575/2890
Processing flight: 576/2890
Processing flight: 577/2890
Processing flight: 578/2890
Processing flight: 579/2890
Processing flight: 580/2890
Processing flight: 581/2890
Processing flight: 582/2890
Processing flight: 583/2890
Processing flight: 584/2890
Processing flight: 585/2890
Processing flight: 586/2890
Processing flight: 587/2890
Processing flight: 588/2890
Processing flight: 589/2890
Processing flight: 590/2890
Processing flight: 591/2890
Processing flight: 592/2890
Processing flight: 593/2890
Processing flight: 594/2890
Processing flight: 595/2890
Processing flight: 596/2890
Processing flight: 597/2890
Processing flight: 598/2890
Processing flight: 599/2890
Processing flight: 600/2890
Processing flight: 601/2890
Processing flight: 602/2890
Processing flight: 603/2890
Processing flight: 604/2890
Processing flight: 605/2890
Processing flight: 606/2890
Processing flight: 607/2890
Processing flight: 608/2890
Processing flight: 609/2890
Processing flight: 610/2890
Processing flight: 611/2890
Processing flight: 612/2890
Processing flight: 613/2890
Processing flight: 614/2890
Processing flight: 615/2890
Processing flight: 616/2890
Processing flight: 617/2890
Processing flight: 618/2890
Processing flight: 619/2890
Processing flight: 620/2890
Processing flight: 621/2890
Processing flight: 622/2890
Processing flight: 623/2890
Processing flight: 624/2890
Processing flight: 625/2890
Processing flight: 626/2890
Processing flight: 627/2890
Processing flight: 628/2890
Processing flight: 629/2890
Processing flight: 630/2890
Processing flight: 631/2890
Processing flight: 632/2890
Processing flight: 633/2890
Processing flight: 634/2890
Processing flight: 635/2890
Processing flight: 636/2890
Processing flight: 637/2890
Processing flight: 638/2890
Processing flight: 639/2890
Processing flight: 640/2890
Processing flight: 641/2890
Processing flight: 642/2890
Processing flight: 643/2890
Processing flight: 644/2890
Processing flight: 645/2890
Processing flight: 646/2890
Processing flight: 647/2890
Processing flight: 648/2890
Processing flight: 649/2890
Processing flight: 650/2890
Processing flight: 651/2890
Processing flight: 652/2890
Processing flight: 653/2890
Processing flight: 654/2890
Processing flight: 655/2890
Processing flight: 656/2890
Processing flight: 657/2890
Processing flight: 658/2890
Processing flight: 659/2890
Processing flight: 660/2890
Processing flight: 661/2890
Processing flight: 662/2890
Processing flight: 663/2890
Processing flight: 664/2890
Processing flight: 665/2890
Processing flight: 666/2890
Processing flight: 667/2890
Processing flight: 668/2890
Processing flight: 669/2890
Processing flight: 670/2890
Processing flight: 671/2890
Processing flight: 672/2890
Processing flight: 673/2890
Error processing flight /Users/rasmus/Desktop/Fysik/AppliedML2026/Final_project_data/data/ML_data/NBI/FDM data/Arrivals/Nuuk Arrival_ 211425_OY-GRJ_27_02_25_04_00.csv: Start of recording time is on a different day than the landing time. Please adjust the offset or check the flight data.
Processing flight: 674/2890
Processing flight: 675/2890
Processing flight: 676/2890
Processing flight: 677/2890
Processing flight: 678/2890
Processing flight: 679/2890
Processing flight: 680/2890
Processing flight: 681/2890
Processing flight: 682/2890
Processing flight: 683/2890
Processing flight: 684/2890
Processing flight: 685/2890
Processing flight: 686/2890
Processing flight: 687/2890
Processing flight: 688/2890
Processing flight: 689/2890
Processing flight: 690/2890
Processing flight: 691/2890
Processing flight: 692/2890
Processing flight: 693/2890
Processing flight: 694/2890

In [9]:
alldata = pd.read_csv('AppMLFinalProject.csv')

In [11]:
alldata.head()

,DateTime,PcTime,ArrRwy04,ArrRwy22,DepRwy22,DepRwy04,ArrRwy04DepRwy22,ArrRwy22DepRwy04,W04.VectorMeanWindSpeed,W04.VectorMeanWindDirection,...,W22.ScalarMaxWindSpeed,W22.ScalarMaxWindAtDirection,W22.ScalarMeanWindSpeed,W22.ScalarWindSpeedDeviation,W22.ScalarMeanWindDirection,W22.ScalarWindDirectionDeviation,W22.LastWindSpeed,W22.LastWindDirection,W22.OkPct,source_file
0,2024-11-28 12:04:29,2024-11-28 10:04:30,2,2,2,2,0,0,3.446184,65.886639,...,9.1,36,7.655263,0.986940,42.496327,6.344822,7.5,38,95.0,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...
1,2024-11-28 12:04:35,2024-11-28 10:04:35,2,2,2,2,0,0,3.477918,66.050344,...,9.1,36,7.613158,1.000045,42.311610,6.212914,6.7,45,95.0,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...
2,2024-11-28 12:04:38,2024-11-28 10:04:40,2,2,2,2,0,0,3.500163,66.170129,...,9.1,36,7.584211,1.027139,42.152913,6.245114,6.1,38,95.0,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...
3,2024-11-28 12:04:44,2024-11-28 10:04:45,2,2,2,2,0,0,3.582905,66.839029,...,9.1,36,7.544737,1.070587,41.626817,5.860641,6.2,41,95.0,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...
4,2024-11-28 12:04:50,2024-11-28 10:04:50,2,2,2,2,0,0,3.604055,67.683592,...,9.1,36,7.636842,0.996948,41.207986,5.333008,7.7,44,95.0,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...

In [14]:
df_ny = alldata.groupby('source_file').agg(mean_vector_speed=('W04.VectorMeanWindSpeed', 'mean'))

df_ny

                                                    mean_vector_speed
source_file
/Users/rasmus/Desktop/Fysik/AppliedML2026/Final...           5.553461
/Users/rasmus/Desktop/Fysik/AppliedML2026/Final...           2.643749
/Users/rasmus/Desktop/Fysik/AppliedML2026/Final...           1.846983
/Users/rasmus/Desktop/Fysik/AppliedML2026/Final...           1.224865
/Users/rasmus/Desktop/Fysik/AppliedML2026/Final...           0.634475
...                                                               ...
/Users/rasmus/Desktop/Fysik/AppliedML2026/Final...          10.904864
/Users/rasmus/Desktop/Fysik/AppliedML2026/Final...           0.569633
/Users/rasmus/Desktop/Fysik/AppliedML2026/Final...           7.972804
/Users/rasmus/Desktop/Fysik/AppliedML2026/Final...           7.996647
/Users/rasmus/Desktop/Fysik/AppliedML2026/Final...           3.801579

[2856 rows x 1 columns]