In [2]:
from helper_functions import *
import sys
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [3]:
data_dir = '/Users/rasmus/Desktop/Fysik/AppliedML2026/Final_project_data/data/ML_data/NBI/FDM data'

df = import_flight_data(data_dir=data_dir,limit=1, recursive=True)

In [4]:
df.head()

,year,month,day,hour,minute,second,vert_acc,radio_altitude,source_file
0,2024.0,11.0,28.0,12.0,14.0,26.0,1.06,1483.7,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...
1,2024.0,11.0,28.0,12.0,14.0,27.0,0.98,1463.0,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...
2,2024.0,11.0,28.0,12.0,14.0,28.0,0.94,1432.5,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...
3,2024.0,11.0,28.0,12.0,14.0,29.0,1.05,1406.9,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...
4,2024.0,11.0,28.0,12.0,14.0,30.0,1.02,1389.8,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...

In [5]:
N_arrivals_tot = 3140-70

full_arrival_data = import_flight_data(data_dir=data_dir, limit=N_arrivals_tot, recursive=True)

In [6]:
full_arrival_data.head()
full_arrival_data['g_deviation'] = np.abs(full_arrival_data['vert_acc']-1)
full_arrival_data.head(20)

,year,month,day,hour,minute,second,vert_acc,radio_altitude,source_file,g_deviation
0,2024.0,11.0,28.0,12.0,14.0,26.0,1.06,1483.7,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...,0.06
1,2024.0,11.0,28.0,12.0,14.0,27.0,0.98,1463.0,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...,0.02
2,2024.0,11.0,28.0,12.0,14.0,28.0,0.94,1432.5,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...,0.06
3,2024.0,11.0,28.0,12.0,14.0,29.0,1.05,1406.9,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...,0.05
4,2024.0,11.0,28.0,12.0,14.0,30.0,1.02,1389.8,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...,0.02
5,2024.0,11.0,28.0,12.0,14.0,31.0,1.03,1371.5,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...,0.03
6,2024.0,11.0,28.0,12.0,14.0,32.0,1.02,1344.7,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...,0.02
7,2024.0,11.0,28.0,12.0,14.0,33.0,1.11,1298.3,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...,0.11
8,2024.0,11.0,28.0,12.0,14.0,34.0,1.00,1280.0,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...,0.00
9,2024.0,11.0,28.0,12.0,14.0,35.0,1.02,1320.3,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...,0.02
10,2024.0,11.0,28.0,12.0,15.0,36.0,0.97,1316.6,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...,0.03
11,2024.0,11.0,28.0,12.0,15.0,37.0,0.95,1358.1,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...,0.05
12,2024.0,11.0,28.0,12.0,15.0,38.0,0.98,1387.4,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...,0.02
13,2024.0,11.0,28.0,12.0,15.0,39.0,1.00,1405.7,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...,0.00
14,2024.0,11.0,28.0,12.0,15.0,40.0,1.03,1445.9,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...,0.03
15,2024.0,11.0,28.0,12.0,15.0,41.0,1.08,1437.4,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...,0.08
16,2024.0,11.0,28.0,12.0,15.0,42.0,1.00,1425.2,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...,0.00
17,2024.0,11.0,28.0,12.0,15.0,43.0,1.19,1411.8,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...,0.19
18,2024.0,11.0,28.0,12.0,15.0,44.0,1.06,1398.3,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...,0.06
19,2024.0,11.0,28.0,12.0,15.0,45.0,1.04,1386.1,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...,0.04

In [8]:
y_df = full_arrival_data.groupby('source_file').agg(year=('year', 'first'), month=('month', 'first'), day=('day', 'first'), hour=('hour', 'first'), minute=('minute', 'first'), second=('second', 'first'), 
                                                    max_vert_acc = ('g_deviation', 'max'), 
                                                    rms_vert_acc = ('g_deviation', lambda x: np.sqrt(np.mean(x**2))), 
                                                    vert_acc_p95 = ('g_deviation', lambda x: np.percentile(x, 95)), 
                                                    source_file=('source_file', 'first'))

y_df['bottom_rms'] = full_arrival_data[full_arrival_data['radio_altitude'] <= 250].groupby('source_file')['g_deviation'].apply(lambda x: np.sqrt(np.mean(x**2)))
y_df.head()

,year,month,day,hour,minute,second,max_vert_acc,rms_vert_acc,vert_acc_p95,source_file,bottom_rms
source_file,,,,,,,,,,,
/Users/rasmus/Desktop/Fysik/AppliedML2026/Final_project_data/data/ML_data/NBI/FDM data/Arrivals/Nuuk Arrival_ 207724_OY-GRH_28_11_24_16_12.csv,2024.0,11.0,28.0,12.0,14.0,26.0,0.19,0.055145,0.1100,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...,0.081807
/Users/rasmus/Desktop/Fysik/AppliedML2026/Final_project_data/data/ML_data/NBI/FDM data/Arrivals/Nuuk Arrival_ 207725_OY-GRP_28_11_24_43_11.csv,2024.0,11.0,28.0,11.0,42.0,45.0,0.11,0.032950,0.0710,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...,0.049329
/Users/rasmus/Desktop/Fysik/AppliedML2026/Final_project_data/data/ML_data/NBI/FDM data/Arrivals/Nuuk Arrival_ 207731_OY-GRG_28_11_24_41_14.csv,2024.0,11.0,28.0,14.0,39.0,34.0,0.11,0.029877,0.0695,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...,0.053944
/Users/rasmus/Desktop/Fysik/AppliedML2026/Final_project_data/data/ML_data/NBI/FDM data/Arrivals/Nuuk Arrival_ 207732_OY-GRK_28_11_24_31_15.csv,2024.0,11.0,28.0,15.0,29.0,4.0,0.18,0.042426,0.0785,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...,0.081179
/Users/rasmus/Desktop/Fysik/AppliedML2026/Final_project_data/data/ML_data/NBI/FDM data/Arrivals/Nuuk Arrival_ 207734_OY-GRH_28_11_24_56_15.csv,2024.0,11.0,28.0,15.0,54.0,4.0,0.17,0.052773,0.1000,/Users/rasmus/Desktop/Fysik/AppliedML2026/Fina...,0.061319

In [9]:
y_df.head()
from pathlib import Path

output_path = Path.cwd().parent / "y_data_rms.csv"
y_df.to_csv(output_path, index=False)

In [27]:
wind_data = pd.read_csv('/Users/rasmus/Desktop/Fysik/AppliedML2026/AppMLFinalProject/All_wind_data_2.csv')
y_df = pd.read_csv('/Users/rasmus/Desktop/Fysik/AppliedML2026/AppMLFinalProject/y_data.csv')

In [29]:
wind_files = wind_data['source_file'].unique()
y_files = y_df['source_file'].unique()
shared_files = np.intersect1d(wind_files, y_files)

y_df_shared = y_df[y_df['source_file'].isin(shared_files)]

y_df_shared.to_csv(Path.cwd().parent / "y_data_2.csv", index=False)

In [15]:
import pandas as pd
import numpy as np
susfile = pd.read_csv('/Users/rasmus/Desktop/Fysik/AppliedML2026/Final_project_data/data/ML_data/NBI/FDM data/Arrivals/Nuuk Arrival_ 209598_OY-GRH_14_01_25_01_19.csv')

print(susfile['GMT - Minutes (BCD)'].dropna().tolist())

np.unique(susfile['GMT - Minutes (BCD)'].dropna().tolist())

[52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 52.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 53.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 54.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 57.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 59.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0]

array([ 0.,  1.,  2., 52., 53., 54., 55., 56., 57., 58., 59., 60.])

In [16]:
def extract_wind_data(flight_df, data_dir, offset=10): 
    """
    Extracts wind data from the TWI dataset for a given flight, based on the landing time and an offset for the recording start time.
    Args:
        flight_df (pd.DataFrame): A DataFrame containing data for one flight, including landing time information.
        data_dir (str): The directory containing the wind data files.
        offset (int): The number of minutes before the landing time to start recording wind data. Default is 10 minutes.
    Returns:
        pd.DataFrame: A DataFrame containing the wind data for the specified time range.
    """

    first = flight_df.iloc[0]

    month = first['month'].astype(int)
    day = first['day'].astype(int)
    if day < 10:
        day_string = '0'+str(day)
    else:
        day_string = str(day)

    if month < 10:
        month_string = '0'+str(month)
    else:        
        month_string = str(month)

    year = first['year'].astype(int)
    start_h = first['hour'].astype(int)
    start_m = first['minute'].astype(int)
    start_s = first['second'].astype(int)

    print(year,
    month,
    day,
    start_h,
    start_m,
    start_s)

    start_of_landing_time = pd.Timestamp(year=year,month=month,day=day,hour=start_h,minute=start_m,second=start_s)

    start_of_recording_time = start_of_landing_time - pd.Timedelta(minutes=offset)
    
    if start_of_recording_time.day != start_of_landing_time.day:
        raise ValueError("Start of recording time is on a different day than the landing time. Please adjust the offset or check the flight data.")
    
    date_string = str(year)+'-'+month_string+'-'+day_string
    file_string = 'TWI-'+date_string+'_UTC_log.csv'

    wind_df = pd.read_csv(data_dir + '/' + file_string, sep=';')

    wind_df['DateTime'] = pd.to_datetime(wind_df['DateTime'], format='%Y-%m-%d %H:%M:%S')

    mask_time = (wind_df['DateTime'] >= start_of_recording_time) & (wind_df['DateTime'] <= start_of_landing_time)

    wind_df = wind_df.loc[mask_time].reset_index(drop=True)
    return wind_df

wind_dir = '/Users/rasmus/Desktop/Fysik/AppliedML2026/Final_project_data/data/ML_data/TWI data'

In [17]:
COLUMN_MAP = {
    # time
    "Year": "year",
    "QAR YEAR": "year",
    "Date: Year (Derived)": "year",

    "MONTH": "month",
    "QAR MONTH": "month",
    "Date (month)": "month",

    "DAY": "day",
    "QAR DAY": "day",
    "Date (day)": "day",

    "GMT - Hours (BCD)": "hour",
    "QAR HOUR": "hour",
    "UTC Hours": "hour",

    "GMT - Minutes (BCD)": "minute",
    "QAR MINUTE": "minute",
    "UTC Minutes": "minute",

    "GMT Seconds": "second",
    "QAR SECOND": "second",
    "UTC Seconds": "second",

    # altitude
    "Radio Altitude": "radio_altitude",
    "Radio Height 1": "radio_altitude",

    # vertical acceleration
    "Vertical Acceleration": "vert_acc",
    "Normal acceleration": "vert_acc",}

susfile.columns = [COLUMN_MAP.get(c, c) for c in susfile.columns]       
needed = ['year','month','day','hour','minute','second','vert_acc','radio_altitude']
susfile = susfile[[c for c in needed if c in susfile.columns]]   
susfile = susfile[susfile['second'].notna()]
susfile.head()
extract_wind_data(susfile, data_dir=wind_dir, offset=10)

2025 1 14 18 52 54

,DateTime,PcTime,ArrRwy04,ArrRwy22,DepRwy22,DepRwy04,ArrRwy04DepRwy22,ArrRwy22DepRwy04,W04.VectorMeanWindSpeed,W04.VectorMeanWindDirection,...,W22.VectorMeanWindDirection,W22.ScalarMaxWindSpeed,W22.ScalarMaxWindAtDirection,W22.ScalarMeanWindSpeed,W22.ScalarWindSpeedDeviation,W22.ScalarMeanWindDirection,W22.ScalarWindDirectionDeviation,W22.LastWindSpeed,W22.LastWindDirection,W22.OkPct
0,2025-01-14 18:42:55,2025-01-14 16:42:56,2,2,2,2,0,0,5.765747,3.990579,...,341.886889,5.8,338,4.976316,0.449230,341.707437,5.087919,5.3,340,95.0
1,2025-01-14 18:43:01,2025-01-14 16:43:01,2,2,2,2,0,0,5.789069,4.127352,...,341.832254,5.8,338,4.976316,0.449815,341.654650,5.063257,5.0,344,95.0
2,2025-01-14 18:43:06,2025-01-14 16:43:06,2,2,2,2,0,0,5.823197,4.334104,...,341.702397,5.8,338,4.976316,0.449815,341.522790,4.985043,4.9,342,95.0
3,2025-01-14 18:43:10,2025-01-14 16:43:11,2,2,2,2,0,0,5.805122,4.455846,...,341.652778,5.8,338,4.978947,0.449068,341.470067,4.946946,4.9,344,95.0
4,2025-01-14 18:43:16,2025-01-14 16:43:16,2,2,2,2,0,0,5.818325,4.481496,...,341.325996,5.8,338,4.973684,0.449376,341.127526,4.725842,4.7,340,95.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,2025-01-14 18:52:31,2025-01-14 16:52:32,2,2,2,2,0,0,5.406523,358.122661,...,334.878603,5.0,326,4.558974,0.266716,334.894226,4.956628,4.8,330,97.5
116,2025-01-14 18:52:36,2025-01-14 16:52:37,2,2,2,2,0,0,5.438584,357.801942,...,334.845388,5.0,326,4.560526,0.271971,334.865086,5.052007,4.8,331,95.0
117,2025-01-14 18:52:40,2025-01-14 16:52:41,2,2,2,2,0,0,5.476527,357.455618,...,334.768414,5.0,326,4.560526,0.269052,334.785911,5.089247,4.7,332,95.0
118,2025-01-14 18:52:46,2025-01-14 16:52:46,2,2,2,2,0,0,5.494002,357.260005,...,335.000229,5.0,339,4.561538,0.261765,334.996378,4.823191,4.8,336,97.5
119,2025-01-14 18:52:51,2025-01-14 16:52:51,2,2,2,2,0,0,5.498846,356.953441,...,335.350567,5.0,339,4.571053,0.263487,335.338116,4.598922,4.8,337,95.0

In [18]:
wind_df = extract_wind_data(susfile, data_dir=wind_dir, offset=10)
 
wind_df['Datetime'] = pd.to_datetime(wind_df['DateTime'], format='%Y-%m-%d %H:%M:%S')

2025 1 14 18 52 54